// Generated from Victoria 3 vanilla files and tyrone-mp. Vanilla loads first; tyrone-mp overrides duplicate keys.
export const COUNTRY_LOCALIZATION_COUNT = 1313;

export const COUNTRY_LOCALIZATION: Record<string, string> = {
  "ABK": "Abkhazia",
  "ABS": "Absaroka",
  "ABU": "Trucial States",
  "ACE": "Aceh",
  "ACH": "Acholi",
  "ADG": "Kel Adagh",
  "ADR": "Adrar",
  "AFG": "Afghanistan",
  "AFS": "Free State",
  "AGC": "Angoche",
  "AGJ": "Angola Janga",
  "AHG": "Kel Ahaggar",
  "AHU": "Anhui",
  "AIN": "Ainu Mosir",
  "AIR": "Kel Air",
  "AIT": "Ait Abbas",
  "AJJ": "Kel Ajjer",
  "AJR": "Ajuran",
  "ALA": "Alba",
  "ALB": "Albania",
  "ALD": "Algeria",
  "ALI": "Altai",
  "ALK": "Alaska",
  "ALT": "Los Altos",
  "ALW": "Alwar",
  "AMZ": "Amazonia",
  "ANH": "Anhalt",
  "ANK": "Ankole",
  "ANL": "Andalusia",
  "ANU": "Anuak",
  "AOT": "Aotearoa",
  "APC": "Apache",
  "ARA": "Arabia",
  "ARB": "Arabistan",
  "ARG": "Argentina",
  "ARH": "Arnhem",
  "ARK": "Arakan",
  "ARM": "Armenia",
  "ARN": "Aragon",
  "ARP": "Arapaho",
  "ARR": "Arrernte",
  "ARS": "Arsiland",
  "ASA": "New Africa",
  "ASH": "Ashanti",
  "ASM": "Assam",
  "ASS": "Assyria",
  "AST": "Australia",
  "ASU": "Asturias",
  "ATB": "Athabaska",
  "ATL": "Antillean Confederation",
  "ATR": "Kel Ataram",
  "AUL": "Aulihan",
  "AUS": "Austria",
  "AWA": "Awadh",
  "AWS": "Aussa",
  "AYI": "Anyi",
  "AYM": "Aymara",
  "AZB": "Azerbaijan",
  "BAD": "Baden",
  "BAG": "Rewah",
  "BAH": "Bahamas",
  "BAL": "Bali",
  "BAS": "Bastar",
  "BAV": "Bavaria",
  "BCE": "Ceylon",
  "BEI": "Beiyang",
  "BEL": "Belgium",
  "BEN": "Benin",
  "BER": "Baroda",
  "BGI": "Bagirmi",
  "BGL": "Bengal",
  "BGM": "Begemder",
  "BHI": "Bahia",
  "BHN": "Bahrain",
  "BHO": "Bhopal",
  "BHT": "India",
  "BHU": "Bhutan",
  "BHV": "Bhavnagar",
  "BHW": "Bahawalpur",
  "BIC": "East India",
  "BIH": "Bihar",
  "BIK": "Bikaner",
  "BJA": "Beja",
  "BKR": "Bashkiria",
  "BLA": "Bilua",
  "BLE": "Baule",
  "BLF": "Niitsitapi",
  "BLG": "Bulungan",
  "BLH": "Baluchistan",
  "BMB": "Bemba",
  "BMM": "Bamum",
  "BND": "Bundu",
  "BNG": "Bangala",
  "BNJ": "Banjar",
  "BNN": "Pannakwati",
  "BNT": "Banat",
  "BNY": "Bunyoro",
  "BOB": "Bobangi",
  "BOH": "Bohemia",
  "BOL": "Bolivia",
  "BOR": "Bornu",
  "BOS": "Bosnia-Herzegovina",
  "BRA": "Brunswick",
  "BRD": "Burundi",
  "BRE": "Bremen",
  "BRG": "Borgu",
  "BRI": "Brittany",
  "BRK": "Brakna",
  "BRN": "Borana",
  "BRU": "Brunei",
  "BRY": "Buryatia",
  "BRZ": "Brazil",
  "BSS": "Bassa",
  "BST": "Basutoland",
  "BTG": "Batonga",
  "BTN": "Buton",
  "BUG": "Buganda",
  "BUK": "Bukhara",
  "BUL": "Bulgaria",
  "BUN": "Orchha",
  "BUR": "Burma",
  "BYE": "Belarus",
  "BYZ": "Byzantium",
  "CAL": "California",
  "CAM": "Cambodia",
  "CAN": "Canada",
  "CAR": "Carnatic",
  "CAS": "Castile",
  "CAT": "Catalonia",
  "CAU": "Transcaucasia",
  "CAY": "Cayor",
  "CCM": "O’odham Country",
  "CEY": "Sri Lanka",
  "CHC": "Chechnya",
  "CHE": "Cherokee",
  "CHI": "China",
  "CHK": "Chokwe",
  "CHL": "Chile",
  "CHP": "Champasak",
  "CHT": "Chitral",
  "CHV": "Chuvashia",
  "CHW": "Chewa",
  "CIR": "Circassia",
  "CKC": "Chukotka",
  "CLI": "Carolina",
  "CLM": "Colombia",
  "CMB": "Chaamba",
  "CMI": "Chiang Mai",
  "CNW": "Cornwall",
  "COB": "Saxe-Coburg-Gotha",
  "COC": "Cochin",
  "COL": "Columbia",
  "COM": "Comanche",
  "CON": "Constantine",
  "COO": "Cooch Behar",
  "COR": "Corsica",
  "COS": "Costa Rica",
  "CRE": "Crete",
  "CRI": "Crimea",
  "CRO": "Croatia",
  "CSA": "Confederate States of America",
  "CSC": "Cascadia",
  "CTF": "Council of Three Fires",
  "CTR": "Santa Catarina",
  "CUB": "Cuba",
  "CYP": "Cyprus",
  "CYR": "Cyrenaica",
  "CZH": "Czechoslovakia",
  "DAG": "Dagestan",
  "DAH": "Dahomey",
  "DAI": "Dai Nam",
  "DAK": "Dar al Kuti",
  "DEI": "East Indies",
  "DEN": "Denmark",
  "DES": "Deseret",
  "DFR": "Darfur",
  "DFT": "Dar Fertit",
  "DGR": "Degar",
  "DHA": "Dharampur",
  "DIN": "Kel Dinnik",
  "DIO": "Diola",
  "DIR": "Dir",
  "DKT": "Dakota",
  "DLA": "Duala",
  "DLM": "Delim",
  "DLY": "Daly",
  "DNK": "Dinka",
  "DOM": "Santo Domingo",
  "DON": "Don Cossack Host",
  "DRA": "Dravida Nadu",
  "DYB": "Dyribal",
  "DZG": "Danzig",
  "ECU": "Ecuador",
  "EDE": "Eden",
  "EGY": "Egypt",
  "ELS": "El Salvador",
  "ENG": "England",
  "EOT": "Emirate of Transjordan",
  "EQT": "Confederation of the Equator",
  "EQU": "Equatoria",
  "EST": "Estonia",
  "ETH": "Ethiopia",
  "EWE": "Ewe",
  "EZO": "Ezochi",
  "FER": "Far East",
  "FIN": "Finland",
  "FJI": "Fiji",
  "FLA": "Flanders",
  "FLR": "Florida",
  "FND": "Federation of the Andes",
  "FNG": "Fang",
  "FRA": "France",
  "FRM": "Frankfurt",
  "FRS": "Formosa",
  "FSA": "Free States of America",
  "FTJ": "Futa Jallon",
  "FTR": "Futa Toro",
  "FZN": "Fezzan",
  "GAC": "Greater America",
  "GAL": "Galicia-Lodomeria",
  "GAO": "Gao",
  "GAR": "Garhwal",
  "GBR": "Great Britain",
  "GCO": "Gran Colombia",
  "GEO": "Georgia",
  "GER": "Germany",
  "GGO": "Gogo",
  "GJM": "Gojjam",
  "GLD": "Geledi",
  "GLI": "Galicia",
  "GML": "Gamilaraay",
  "GNG": "Da Cheng",
  "GNI": "Guarani",
  "GOGU": "Goguryeo",
  "GRE": "Greece",
  "GRG": "Georgia",
  "GRI": "Guarani",
  "GRN": "Greenland",
  "GRW": "Garawa",
  "GUA": "Guatemala",
  "GUI": "Guizhou",
  "GUJ": "Gujarat",
  "GWA": "Gwalior",
  "GZA": "Gaza",
  "HAI": "Haiti",
  "HAM": "Hamburg",
  "HAN": "Hanover",
  "HAR": "Harar",
  "HAU": "Gobir",
  "HAW": "Hawaii",
  "HBC": "Hudson's Bay Company",
  "HDJ": "Hedjaz",
  "HDY": "Hadiya",
  "HEK": "Hesse-Kassel",
  "HER": "Herat",
  "HES": "Hesse",
  "HHE": "Hehe",
  "HLA": "Halia",
  "HMB": "Hemba",
  "HNA": "Hunan",
  "HND": "India",
  "HOB": "Hobyo",
  "HOH": "Hohenzollern",
  "HOL": "Holstein",
  "HON": "Honduras",
  "HRE": "Central Europe",
  "HRO": "Herero",
  "HTH": "Hathawaddy",
  "HUN": "Hungary",
  "HYD": "Hyderabad",
  "HZJ": "Hazarajat",
  "IBE": "Iberia",
  "IBL": "Ibibioland",
  "IBO": "Igbo",
  "ICL": "Iceland",
  "IDA": "Idar",
  "IDN": "Indonesia",
  "IDS": "Indusstan",
  "IND": "Indore",
  "ION": "Ionian Islands",
  "IQU": "Iquicha",
  "IRC": "Iron Confederacy",
  "IRE": "Ireland",
  "IRO": "Haudenosaunee",
  "IRQ": "Iraq",
  "ISQ": "Isaaq",
  "ISR": "Israel",
  "ITA": "Italy",
  "IUS": "Idel-Ural",
  "JAB": "Jabal Shammar",
  "JAI": "Dhundhar",
  "JAM": "Jamaica",
  "JAN": "Jan Mayen",
  "JAP": "Japan",
  "JAS": "Jaisalmer",
  "JAV": "Java",
  "JEY": "Jeypore",
  "JHN": "Jhansi",
  "JLF": "Jolof",
  "JMB": "Jambi",
  "JOD": "Marwar",
  "JOH": "Johore",
  "JRR": "Jarrak",
  "JUN": "Junagadh",
  "KAB": "Kabul",
  "KAF": "Kafiristan",
  "KAL": "Kalat",
  "KAN": "Kandahar",
  "KAS": "Kashmir",
  "KAT": "Kathiri",
  "KAU": "Kaurna",
  "KAZ": "Kazakhstan",
  "KBA": "Kuba",
  "KBD": "Kabadougou",
  "KBU": "Kaabu",
  "KFA": "Kaffa",
  "KHI": "Khiva",
  "KHM": "Khmu",
  "KHN": "Kachin",
  "KHP": "Kolhapur",
  "KHR": "Kharan",
  "KKI": "Kuki",
  "KKT": "Kalkatungu",
  "KKY": "Kikuyu",
  "KLM": "Kalmykia",
  "KLN": "Kulin",
  "KLO": "Khmer Loeu",
  "KLT": "Kalimantan",
  "KMC": "Kamchatka",
  "KNC": "Karna",
  "KNG": "Kong",
  "KNK": "Kanak",
  "KNO": "Kurnool",
  "KNT": "Kanty-Mansi",
  "KOK": "Kokand",
  "KON": "Kongo",
  "KOR": "Korea",
  "KOT": "Kotah",
  "KPR": "Khairpur",
  "KRA": "Krakow",
  "KRG": "Karagwe",
  "KRI": "Douriango",
  "KRL": "Karelia",
  "KRN": "Karen",
  "KRT": "Kaarta",
  "KRU": "Kru",
  "KSN": "Kasanje",
  "KSS": "Kissi",
  "KTI": "Kutai",
  "KTU": "Kartu",
  "KUK": "Danubian State",
  "KUN": "Kunduz",
  "KUR": "Kurdistan",
  "KUT": "Kutch",
  "KYN": "Pilbara",
  "KYR": "Kirgizia",
  "KZH": "Kishi Zhuz",
  "KZM": "Kazembe",
  "LAD": "Ladakh",
  "LAH": "Lahej",
  "LAN": "Lanfang",
  "LAO": "Laos",
  "LAT": "Latvia",
  "LBA": "Luba",
  "LBL": "Las Bela",
  "LBY": "Libya",
  "LEB": "Lebanon",
  "LEO": "León",
  "LGA": "Lega",
  "LIB": "Liberia",
  "LIM": "Limburg",
  "LIP": "Lippe",
  "LIT": "Lithuania",
  "LKT": "Lakota",
  "LMV": "Lombardy-Venetia",
  "LMW": "Lomwe",
  "LND": "Lunda",
  "LNG": "Loango",
  "LOM": "Lombardia",
  "LOU": "Louisiana",
  "LRR": "Larrakia",
  "LUA": "Luang Prabang",
  "LUB": "Lübeck",
  "LUC": "Lucca",
  "LUO": "Luo",
  "LUR": "Luristan",
  "LUX": "Luxembourg",
  "LZO": "Barotse",
  "MAD": "Madagascar",
  "MAH": "Mahra",
  "MAI": "Maimana",
  "MAK": "Makran",
  "MAL": "Mali",
  "MAS": "Mascara",
  "MAY": "Maya",
  "MAZ": "Mazandaran",
  "MBS": "Mombasa",
  "MCH": "Manchuria",
  "MCO": "Michoacán",
  "MCR": "Micronesia",
  "MDI": "Mirndi",
  "MDK": "Mandinka",
  "MEC": "Mecklenburg",
  "MEI": "Saxe-Meiningen",
  "MEW": "Mewar",
  "MEX": "Mexico",
  "MGB": "Maghreb",
  "MGD": "Maguindanao",
  "MGH": "Khasi",
  "MGL": "Mongolia",
  "MHR": "Maharashtra",
  "MJK": "Mijikenda",
  "MJT": "Majerteen",
  "MKT": "Miskitia",
  "MKU": "Makua",
  "MLD": "Maldives",
  "MLT": "Malta",
  "MNB": "Mangbetu",
  "MNC": "Manica",
  "MND": "Mindanao",
  "MNG": "Minas Gerais",
  "MNP": "Manipur",
  "MOD": "Modena",
  "MOL": "Moldavia",
  "MON": "Montenegro",
  "MOR": "Morocco",
  "MOS": "Mossi",
  "MPH": "Muang Phuan",
  "MRA": "Mara",
  "MRD": "Erzya-Moksha",
  "MRI": "Mari El",
  "MRN": "Mirning",
  "MRV": "Maravi",
  "MSC": "Muscogee",
  "MSH": "Mashona",
  "MSI": "Masai",
  "MSK": "Maseko",
  "MSN": "Massina",
  "MST": "Mecklenburg-Strelitz",
  "MTB": "Ndebele",
  "MTC": "Métis",
  "MTP": "Mutapa",
  "MUG": "Hindustan",
  "MUI": "Muisca",
  "MYB": "Mayurbhanj",
  "MYI": "Mayi",
  "MYS": "Mysore",
  "MZB": "Mzab",
  "NAG": "Nagpur",
  "NAH": "Anahuac",
  "NAL": "Natalia",
  "NAM": "Nama",
  "NAR": "Narsinghpur",
  "NAS": "Nassau",
  "NAV": "Navarra",
  "NAW": "Nawanagar",
  "NBA": "Nuba",
  "NBS": "New Brunswick",
  "NCA": "Mountain Republic",
  "NCR": "North Carolina",
  "NEJ": "Nejd",
  "NEN": "New England",
  "NEP": "Nepal",
  "NET": "Netherlands",
  "NEW": "Newfoundland",
  "NGA": "Naga",
  "NGF": "North German Federation",
  "NGU": "Ngarru",
  "NIC": "Nicaragua",
  "NNG": "Noongar",
  "NNV": "Nunavut",
  "NOR": "Norway",
  "NPU": "North Peru",
  "NRU": "Nauru",
  "NSW": "New South Wales",
  "NTO": "Ngāti Toa",
  "NTU": "Ngāi Tahu",
  "NUE": "Nuer",
  "NVJ": "Navajo",
  "NVL": "Navajoland",
  "NVS": "Nova Scotia",
  "NYL": "Nyulnyulan",
  "NYM": "Unyamwezi",
  "NYP": "Ngumpin-Yapa",
  "NYR": "Ngayarda",
  "NZL": "New Zealand",
  "NZP": "Nimíipuu",
  "OAX": "Oaxaca",
  "OCC": "Occitania",
  "OGD": "Ogaden",
  "OLD": "Oldenburg",
  "OMA": "Oman",
  "OMO": "Omo",
  "ONT": "Ontario",
  "ORA": "Oranje",
  "ORG": "Oregon",
  "ORI": "Orissa",
  "ORM": "Orma",
  "ORN": "Orinoco",
  "OUA": "Tagant",
  "OVB": "Ovambo",
  "OVM": "Ovimbundu",
  "OYO": "Oyo",
  "OZH": "Orta Zhuz",
  "PAA": "Paakintyi",
  "PAK": "Pakistan",
  "PAL": "Palestine",
  "PAN": "Punjab",
  "PAP": "Rome",
  "PAR": "Parma",
  "PAT": "Mapuche",
  "PAU": "Paulistânia",
  "PBC": "Peru-Bolivia",
  "PCO": "Puerto Rico",
  "PDI": "Pedi",
  "PER": "Persia",
  "PEU": "Peru",
  "PHI": "Philippines",
  "PHL": "Philippolis",
  "PLC": "Poland-Lithuania",
  "PLP": "Palanpur",
  "PLT": "Rio de la Plata",
  "PLY": "Tahiti",
  "PMA": "Pama",
  "PNI": "Piratini",
  "PNM": "Panama",
  "PNS": "Polynesia",
  "POL": "Poland",
  "POM": "Pomerania",
  "PON": "Pontianak",
  "POR": "Portugal",
  "PPU": "Papua",
  "PRA": "Grão-Pará",
  "PRC": "Paris Commune",
  "PRG": "Paraguay",
  "PRK": "Perak",
  "PRM": "Perm",
  "PRU": "Prussia",
  "PTA": "Patiala",
  "PTN": "Patna",
  "PUD": "Pudukottai",
  "PUE": "Pueblo",
  "PWN": "Pawnee",
  "QIA": "Qian",
  "QUE": "Quebec",
  "QWR": "Qwara",
  "RAJ": "Rajputana",
  "RGB": "Reguibat",
  "RHE": "Rhineland",
  "RHN": "Confederation of the Rhine",
  "RIO": "Río Grande",
  "ROM": "Romania",
  "RSM": "San Marco",
  "RUS": "Russia",
  "RWD": "Rwanda",
  "RYU": "Ryukyu",
  "SAF": "South Africa",
  "SAH": "Sahrawi",
  "SAK": "Siak",
  "SAN": "San",
  "SAR": "Sardinia-Piedmont",
  "SAS": "South Australia",
  "SAT": "Satara",
  "SAV": "Savoy",
  "SAX": "Saxony",
  "SC1": "Nueva España",
  "SC2": "Nueva Granada",
  "SC3": "Perú",
  "SC4": "Río de la Plata",
  "SCA": "Scandinavia",
  "SCH": "Schleswig",
  "SCM": "Schaumburg-Lippe",
  "SCN": "Scania",
  "SCO": "Scotland",
  "SCR": "South Carolina",
  "SCT": "Sip Song Chau Tai",
  "SCW": "Schwarzburg",
  "SDM": "Sidamo",
  "SEL": "Selangor",
  "SEQ": "Indian Territory",
  "SER": "Serbia",
  "SGF": "South German Federation",
  "SGU": "Segou",
  "SHA": "Shandong",
  "SHN": "Shanxi",
  "SHS": "Shan",
  "SHW": "Shewa",
  "SIA": "Siam",
  "SIB": "Siberia",
  "SIC": "Two Sicilies",
  "SIH": "Sichuan",
  "SIK": "Sikkim",
  "SIL": "Sierra Leone",
  "SIN": "Sindh",
  "SKH": "Evenki",
  "SKM": "Usukuma",
  "SKY": "Sakuye",
  "SLK": "Selk’nam",
  "SLO": "Slovenia",
  "SLS": "Séliš",
  "SLV": "Slovakia",
  "SLW": "Sulawesi",
  "SMB": "Sambas",
  "SMI": "Sapmi",
  "SML": "Yat’siminoli",
  "SNA": "Sena",
  "SNG": "Sangu",
  "SOK": "Sokoto",
  "SPA": "Spain",
  "SPC": "Carlist Spain",
  "SPU": "South Peru",
  "SRA": "Sara",
  "SRB": "Sorbia",
  "SRK": "Surakarta",
  "SRR": "Serer",
  "SSU": "Susu",
  "STG": "Sintang",
  "SUD": "Sudan",
  "SUL": "Sulu",
  "SUR": "Surguja",
  "SWE": "Sweden",
  "SWI": "Switzerland",
  "SWT": "Swat",
  "SWZ": "Swaziland",
  "SYR": "Syria",
  "TAR": "Tatarstan",
  "TAS": "Tasmania",
  "TBI": "Tubu",
  "TEK": "Tekna",
  "TEX": "Texas",
  "TGI": "Tungi",
  "TGR": "Tigray",
  "THL": "Tehuelche",
  "TIB": "Tibet",
  "TID": "Tidore",
  "TIP": "Tipperah",
  "TIR": "Tiris",
  "TIS": "Turtle Island",
  "TIV": "Tivland",
  "TJI": "Tajikistan",
  "TKE": "Teke",
  "TMN": "Temne",
  "TNG": "Tonga",
  "TNS": "Tungus",
  "TOB": "Toba",
  "TPG": "Heavenly Kingdom",
  "TPI": "Tupinamba",
  "TPS": "Toposa",
  "TRA": "Travancore",
  "TRC": "Turkmenistan",
  "TRE": "Trieste",
  "TRH": "Turkestan",
  "TRI": "Tripolitania",
  "TRK": "Turkana",
  "TRM": "Turkmenia",
  "TRN": "Transvaal",
  "TRS": "Transylvania",
  "TRZ": "Trarza",
  "TSW": "Tswana",
  "TUA": "Tuat",
  "TUG": "Touggourt",
  "TUN": "Tunis",
  "TUR": "Turkey",
  "TUS": "Tuscany",
  "TUV": "Tuva",
  "TWT": "Tawantinsuyu",
  "UBD": "United Baltic Provinces",
  "UCA": "Central America",
  "UDM": "Udmurtia",
  "UKR": "Ukraine",
  "ULR": "Uluru",
  "ULS": "Ulster",
  "ULT": "Ulta",
  "UNL": "United Netherlands",
  "UNSA": "United South America",
  "UNT": "United Tribes",
  "UOM": "Michigan",
  "URL": "Ural",
  "URU": "Uruguay",
  "USA": "America",
  "UTE": "Ute",
  "UTR": "Utetera",
  "UYA": "Uyao",
  "UZB": "Uzbekistan",
  "UZH": "Uly Zhuz",
  "VEN": "Venice",
  "VIE": "Vientiane",
  "VND": "Venda",
  "VNT": "Vanuatu",
  "VNZ": "Venezuela",
  "WAD": "Wadai",
  "WAL": "Wallachia",
  "WAS": "Western Australia",
  "WBL": "Griqualand",
  "WDJ": "Wiradjuri",
  "WEI": "Saxe-Weimar",
  "WES": "Westphalia",
  "WIN": "West Indies",
  "WKB": "Waka-Gabi",
  "WLD": "Waldeck",
  "WLG": "Welega",
  "WLL": "Wallonia",
  "WLO": "Wello",
  "WLS": "Wales",
  "WLT": "Wolaita",
  "WRD": "Wardaman",
  "WRR": "Worrorra",
  "WSG": "Warsangali",
  "WTI": "Anangu",
  "WTU": "Witu",
  "WUR": "Württemberg",
  "WYU": "Wayuu",
  "XHO": "Xhosa",
  "XIB": "Xibei",
  "XIN": "Uyghuristan",
  "XNP": "Naples",
  "YAK": "Yakutia",
  "YEM": "Yemen",
  "YGU": "Yolngu",
  "YKA": "Yaka",
  "YOG": "Yogyakarta",
  "YUC": "Yucatán",
  "YUE": "Yue",
  "YUG": "Yugoslavia",
  "YUN": "Yunnan",
  "YUR": "Yura",
  "YUZ": "Yuanzhumin",
  "YYT": "Yorta Yorta",
  "ZAI": "Azal",
  "ZAN": "Zanzibar",
  "ZHI": "Zhili",
  "ZIM": "Zimbabwe",
  "ZND": "Azande",
  "ZUL": "Zulu",
  "ZWY": "Zuwayya",
  "dyn_c_united_communes_pns": "United Communes of Polynesia",
  "dyn_c_united_sovereign_archduchy": "United Sovereign Archduchy",
  "dyn_c_united_sovereign_archduchy_adj": "Archducal American",
  "dyn_c_united_senators": "United Senators of America",
  "dyn_c_united_states": "United States of America",
  "dyn_c_united_syndicates_of_america": "United Syndicates of America",
  "dyn_c_united_synods_of_america": "United Synods of America",
  "dyn_c_ottoman_empire": "Ottoman Empire",
  "dyn_c_ottoman_empire_adj": "Ottoman",
  "dyn_c_papal_states": "Papal States",
  "dyn_c_papal_states_adj": "Papal",
  "dyn_c_roman_republic": "Roman Republic",
  "dyn_c_upper_canada": "Upper Canada",
  "dyn_c_upper_canada_adj": "Upper Canadian",
  "dyn_c_lower_canada": "Lower Canada",
  "dyn_c_lower_canada_adj": "Lower Canadian",
  "dyn_c_new_granada": "New Granada",
  "dyn_c_new_granada_adj": "New Granadine",
  "dyn_c_soviet_union": "Union of Soviet Socialist Republics",
  "dyn_c_soviet_union_adj": "Soviet",
  "dyn_c_union_of_new_people": "Union of the New People",
  "dyn_c_union_of_new_people_adj": "Nihilist",
  "dyn_c_mexican_empire": "Mexican Empire",
  "dyn_c_confederated_sovereigns_of_america": "Confederated Sovereigns of America",
  "dyn_c_confederated_sovereigns_of_america_adj": "Confederate",
  "dyn_c_communist_states_of_america": "Communist States of America",
  "dyn_c_communist_states_of_america_adj": "Communist American",
  "dyn_c_confederate_synods_of_america": "Confederate Synods of America",
  "dyn_c_great_qing": "Great Qing",
  "dyn_c_great_qing_adj": "Qing",
  "dyn_c_bavarian_raterepublic": "Bavarian Räterepublik",
  "dyn_c_bremener_raterepublic": "Bremener Räterepublik",
  "dyn_c_van_diemans_land": "Van Diemen’s Land",
  "dyn_c_van_diemans_land_adj": "Van Diemen’s Lander",
  "dyn_c_peoples_republic_of_china": "People’s Republic of China",
  "dyn_c_hanover": "Hanover",
  "dyn_c_hanover_adj": "Hanoverian",
  "dyn_c_grand_duchy_of_finland": "Grand Duchy of Finland",
  "dyn_c_congress_poland": "Congress Poland",
  "dyn_c_congress_poland_adj": "Polish",
  "dyn_c_baltic_governorate": "Baltic Governorates",
  "dyn_c_baltic_governorate_adj": "Baltic",
  "dyn_c_saint-domingue": "Saint-Domingue",
  "dyn_c_saint-domingue_adj": "Domingois",
  "dyn_c_new_spain": "New Spain",
  "dyn_c_new_spain_adj": "New Spanish",
  "dyn_c_baku_commune": "Baku Commune",
  "dyn_c_baku_commune_adj": "Bakuvian",
  "dyn_c_centrocaspian_dictatorship": "Centrocaspian Dictatorship",
  "dyn_c_centrocaspian_dictatorship_adj": "Centrocaspian",
  "dyn_c_tunisia": "Tunisia",
  "dyn_c_united_belgian_states": "United Belgian States",
  "dyn_c_moldova": "Moldova",
  "dyn_c_moldova_adj": "Moldovan",
  "dyn_c_comancheria": "Comancheria",
  "dyn_c_comancheria_adj": "Comancherian",
  "dyn_c_austria-hungary": "Austria-Hungary",
  "dyn_c_austria-hungary_adj": "Austro-Hungarian",
  "dyn_c_miskito_kingdom": "Miskito Kingdom",
  "dyn_c_mosquito_kingdom": "Mosquito Kingdom",
  "dyn_c_mosquito_kingdom_adj": "Mosquito",
  "dyn_c_british_commonwealth": "British Commonwealth",
  "dyn_c_british_commonwealth_adj": "Commonwealth",
  "dyn_c_botswana": "Botswana",
  "dyn_c_botswana_adj": "Botswanan",
  "dyn_c_bechuanaland": "Bechuanaland",
  "dyn_c_bechuanaland_adj": "Bechuanalander",
  "dyn_c_hereroland": "Hereroland",
  "dyn_c_hereroland_adj": "Hererolander",
  "dyn_c_german_empire": "German Empire",
  "dyn_c_british_raj": "Raj",
  "dyn_c_british_raj_adj": "Indian",
  "dyn_c_east_india_company": "East India Company",
  "dyn_c_east_india_company_adj": "Indian",
  "dyn_c_east_indies": "East Indies",
  "dyn_c_east_indies_adj": "East Indies",
  "dyn_c_sequoyah": "Sequoyah",
  "dyn_c_sequoyah_adj": "Sequoyah",
  "dyn_c_sicily": "Sicily",
  "dyn_c_sicily_adj": "Sicilian",
  "dyn_c_naples": "Naples",
  "dyn_c_naples_adj": "Neapolitan",
  "dyn_c_free_territory": "Free Territory",
  "dyn_c_free_territory_adj": "Free Territorial",
  "dyn_c_british_republic": "British Republic",
  "dyn_c_etruria": "Etruria",
  "dyn_c_etruria_adj": "Etrurian",
  "dyn_c_transvaal_colony": "Transvaal Colony",
  "dyn_c_orange_river_sovereignty": "Orange River Sovereignty",
  "dyn_c_orange_river_sovereignty_adj": "Orange River",
  "dyn_c_winburg": "Winburg",
  "dyn_c_winburg_adj": "Winburger",
  "dyn_c_lesotho": "Lesotho",
  "dyn_c_lesotho_adj": "Basuto",
  "dyn_c_colony_of_natal": "Colony of Natal",
  "dyn_c_colony_of_natal_adj": "Natalian",
  "dyn_c_potchefstroom": "Potchefstroom",
  "dyn_c_potchefstroom_adj": "Potchefstroomer",
  "dyn_c_cape_of_good_hope": "Cape of Good Hope",
  "dyn_c_cape_of_good_hope_adj": "Cape",
  "dyn_c_union_of_south_africa": "Union of South Africa",
  "dyn_c_union_of_south_africa_adj": "South African",
  "dyn_c_south_african_republic": "South African Republic",
  "dyn_c_south_african_republic_adj": "South African",
  "dyn_c_suid-afrika": "Suid-Afrika",
  "dyn_c_suid-afrika_adj": "Suid-Afrikan",
  "dyn_c_rozvi_empire": "Rozvi",
  "dyn_c_rozvi_empire_adj": "Rozvi",
  "dyn_c_mthwakazi": "Mthwakazi",
  "dyn_c_mthwakazi_adj": "Mthwakazi",
  "dyn_c_waterboersland": "Waterboersland",
  "dyn_c_waterboersland_adj": "Waterboerslander",
  "dyn_c_philippolis_griqua": "Philippolis",
  "dyn_c_philippolis_griqua_adj": "Philippolitan",
  "dyn_c_columbia": "Columbia",
  "dyn_c_columbia_adj": "Columbia",
  "dyn_c_columbia_district": "Columbia District",
  "dyn_c_ruperts_land": "Rupert’s Land",
  "dyn_c_ruperts_land_adj": "Rupertslander",
  "dyn_c_courland": "Courland",
  "dyn_c_courland_adj": "Courlander",
  "dyn_c_sikh_empire": "Khalsa Raj",
  "dyn_c_sikh_empire_adj": "Sikh",
  "dyn_c_khmer_empire": "Khmer Empire",
  "dyn_c_khmer_empire_adj": "Khmer",
  "dyn_c_merina_kingdom": "Merina Kingdom",
  "dyn_c_merina_kingdom_adj": "Merina",
  "dyn_c_saudi_arabia": "Saudi Arabia",
  "dyn_c_saudi_arabia_adj": "Saudi",
  "dyn_c_great_mongolian_state": "Great Mongolian State",
  "dyn_c_great_mongolian_state_adj": "Mongolia",
  "dyn_c_mongolian_peoples_republic": "Mongolian People’s Republic",
  "dyn_c_mongolian_peoples_republic_adj": "Mongolian",
  "dyn_c_united_kingdom": "United Kingdom",
  "dyn_c_united_kingdom_adj": "Luso-Brazilian",
  "dyn_c_congo_free_state": "Congo Free State",
  "dyn_c_congo_free_state_adj": "Congolese",
  "dyn_c_oranje_free_state": "Orange Free State",
  "dyn_c_oranje_free_state_adj": "Orange",
  "dyn_c_zambezi_free_state": "Zambezi Free State",
  "dyn_c_zambezi_free_state_adj": "Zambezi",
  "dyn_c_nile_free_state": "Nile Basin Free State",
  "dyn_c_nile_free_state_adj": "Nile Basin Free State",
  "dyn_c_niger_free_state": "Niger Free State",
  "dyn_c_niger_free_state_adj": "Nigerien",
  "dyn_c_sahara_free_state": "Sahara Free State",
  "dyn_c_sahara_free_state_adj": "Saharan",
  "dyn_c_papal_italy": "Kingdom of Heaven",
  "dyn_c_papal_italy_adj": "Papal",
  "dyn_c_oceti_sakowin": "Great Sioux Nation",
  "dyn_c_oceti_sakowin_adj": "Sioux",
  "dyn_c_korea_joseon": "Joseon",
  "dyn_c_korea_joseon_adj": "Korean",
  "dyn_c_empire_of_korea": "Empire of Korea",
  "dyn_c_empire_of_korea_adj": "Korean",
  "dyn_c_scandinavia_fennoscandia": "Fennoscandia",
  "dyn_c_scandinavia_fennoscandia_adj": "Fennoscandian",
  "dyn_c_chechnya_imamate": "Caucasian Imamate",
  "dyn_c_chechnya_imamate_adj": "Imamate",
  "dyn_c_greater_manchester": "Greater Manchester",
  "dyn_c_greater_manchester_adj": "Magna Mancunian",
  "dyn_c_mancunian_commune": "Mancunian Commune",
  "dyn_c_mancunian_commune_adj": "Mancunian",
  "dyn_c_schleswig_holstein": "Schleswig-Holstein",
  "dyn_c_schleswig_holstein_adj": "Schleswig-Holsteinian",
  "dyn_c_kazakh_republic": "Kazakhstan",
  "dyn_c_kazakh_republic_adj": "Kazakh",
  "dyn_c_kazakh_khanate": "Kazakh Khanate",
  "dyn_c_kazakh_khanate_adj": "Kazakh",
  "dyn_c_kazakh_alash_autonomy": "Alash Autonomy",
  "dyn_c_kazakh_alash_autonomy_adj": "Kazakh",
  "dyn_c_kazakh_steppe_governorate_general": "Governorate General of the Steppes",
  "dyn_c_kazakh_steppe_governorate_general_adj": "Kazakh",
  "dyn_c_lyon": "Lyon",
  "dyn_c_lyon_adj": "Lyonnais",
  "dyn_c_romandy": "Romandy",
  "dyn_c_romandy_adj": "Romand",
  "dyn_c_two_californias": "Two Californias",
  "dyn_c_two_californias_adj": "Californian",
  "dyn_c_ussr_californias": "United Socialist Council Republics of California",
  "dyn_c_ussr_californias_adj": "Californian",
  "dyn_c_french_empire": "French Empire",
  "dyn_c_french_empire_adj": "French",
  "dyn_c_french_republic": "French Republic",
  "dyn_c_french_republic_adj": "French",
  "dyn_c_french_kingdom": "Kingdom of France",
  "dyn_c_french_kingdom_adj": "French",
  "dyn_c_french_commune": "French Commune",
  "dyn_c_french_commune_adj": "Communard",
  "dyn_c_north_american_technate": "Unified Scientific Associations",
  "dyn_c_north_american_technate_adj": "Technate",
  "dyn_c_catharinense_republic": "Catharinense Republic",
  "dyn_c_catharinense_republic_adj": "Catharinense",
  "dyn_c_riograndense_republic": "Riograndense Republic",
  "dyn_c_riograndense_republic_adj": "Riograndense",
  "dyn_c_american_federation": "Federation of the Americas",
  "dyn_c_american_federation_adj": "Americano",
  "dyn_c_united_provinces_of_south_america": "United Provinces of South America",
  "dyn_c_united_provinces_of_south_america_adj": "United Provinces",
  "dyn_c_united_provinces_of_america": "United Provinces of the Americas",
  "dyn_c_united_provinces_of_america_adj": "Americano",
  "dyn_c_republic_of_san_marco": "Republic of San Marco",
  "dyn_c_republic_of_san_marco_adj": "Venetian",
  "dyn_c_hre_republic": "United States of Europe",
  "dyn_c_hre_republic_adj": "Paneuropean",
  "dyn_c_hre_communist": "Union of Council Republics",
  "dyn_c_hre_communist_adj": "Paneuropean",
  "dyn_c_hre_technate": "Pan-European Technate",
  "dyn_c_hre_technate_adj": "Paneuropean",
  "dyn_c_hre_fascist": "Paneuropa",
  "dyn_c_hre_fascist_adj": "Paneuropan",
  "dyn_c_hre_monarchy": "Holy Roman Empire",
  "dyn_c_hre_monarchy_adj": "Holy Roman Empire",
  "dyn_c_hre_monarchy_atheist": "Unholy Roman Empire",
  "dyn_c_hre_monarchy_atheist_adj": "Unholy Roman Empire",
  "dyn_c_united_principalities": "United Principalities",
  "dyn_c_united_principalities_adj": "Romanian",
  "dyn_c_moldavia_and_wallachia": "Moldavia and Wallachia",
  "dyn_c_moldavia_and_wallachia_adj": "Romanian",
  "dyn_c_wallachia_and_moldavia": "Wallachia and Moldavia",
  "dyn_c_wallachia_and_moldavia_adj": "Romanian",
  "dyn_c_burgundy": "Burgundy",
  "dyn_c_burgundy_adj": "Burgundian",
  "dyn_c_great_turtle": "Great Turtle",
  "dyn_c_great_turtle_adj": "Great Turtle",
  "dyn_c_argentine_confederation": "Argentine Confederation",
  "dyn_c_river_plate": "River Plate",
  "dyn_c_river_plate_adj": "Platine",
  "dyn_c_quito": "Quito",
  "dyn_c_quito_adj": "Quiteño",
  "dyn_c_cisplatina": "Cisplatina",
  "dyn_c_cisplatina_adj": "Cisplatine",
  "dyn_c_charcas": "Charcas",
  "dyn_c_charcas_adj": "Charcas",
  "dyn_c_upper_peru": "Upper Peru",
  "dyn_c_upper_peru_adj": "Upper Peruvian",
  "dyn_c_banda_oriental": "Banda Oriental",
  "dyn_c_banda_oriental_adj": "Banda Oriental",
  "dyn_c_klein_venedig": "Klein-Venedig",
  "dyn_c_klein_venedig_adj": "Klein-Venedisch",
  "dyn_c_argentina_legionaria": "Argentina Legionaria",
  "dyn_c_plurinational_bolivia": "Plurinational State of Bolivia",
  "dyn_c_sudamerica_legionaria": "Sudamerica Legionaria",
  "dyn_c_sudamerica_legionaria_adj": "Sudamericano",
  "dyn_c_confederacion_sudamericana": "Confederación Sudamericana",
  "dyn_c_confederacion_sudamericana_adj": "Sudamericano",
  "dyn_c_rsfsr": "Russian Soviet Republic",
  "dyn_c_rsfsr_adj": "Russian",
  "dyn_c_russian_republic": "Russian Republic",
  "dyn_c_russian_republic_adj": "Russian",
  "dyn_c_kartli_kakheti": "Kartli-Kakheti",
  "dyn_c_kartli_kakheti_adj": "Kartli-Kakheti",
  "dyn_c_baku": "Shirvan",
  "dyn_c_baku_adj": "Shirvani",
  "dyn_c_bakhtiari": "Bakhtiari",
  "dyn_c_bakhtiari_adj": "Bakhtiarian",
  "dyn_c_beiyang_government": "Beiyang Government",
  "dyn_c_hunan_clique": "Hunan Clique",
  "dyn_c_guangxi_clique": "Guangxi Clique",
  "dyn_c_anhui_clique": "Anhui Clique",
  "dyn_c_zhili_clique": "Zhili Clique",
  "dyn_c_fengtian_clique": "Fengtian Clique",
  "dyn_c_fengtian_adj": "Fengtian",
  "dyn_c_shanxi_clique": "Shanxi Clique",
  "dyn_c_xinjiang_clique": "Xinjiang Clique",
  "dyn_c_xinjiang_adj": "Xinjiang",
  "dyn_c_guizhou_clique": "Guizhou Clique",
  "dyn_c_guangdong_clique": "Guangdong Clique",
  "dyn_c_guangdong_adj": "Guangdong",
  "dyn_c_sichuan_clique": "Sichuan Clique",
  "dyn_c_shandong_clique": "Shandong Clique",
  "dyn_c_yunnan_clique": "Yunnan Clique",
  "dyn_c_nuristan": "Nuristan",
  "dyn_c_nuristan_adj": "Nuristani",
  "dyn_c_peristan": "Peristan",
  "dyn_c_peristan_adj": "Peristani",
  "dyn_c_jammu": "Jammu",
  "dyn_c_jammu_adj": "Jammuite",
  "dyn_c_alyaska": "Alyaska",
  "dyn_c_alyaska_adj": "Alyaski",
  "dyn_c_russian_american_company": "American Company",
  "dyn_c_russian_american_company_adj": "Russo-American",
  "dyn_c_jammu_and_kashmir": "Jammu and Kashmir",
  "dyn_c_shan_states": "Federated Shan States",
  "dyn_c_shan_states_adj": "Shan",
  "dyn_c_dominion_of_india": "Dominion of India",
  "dyn_c_dominion_of_india_adj": "Indian",
  "dyn_c_bengal_free_state": "Bengal Free State",
  "dyn_c_bengal_free_state_adj": "Bengali",
  "dyn_c_confederacy_of_india": "Confederacy of India",
  "dyn_c_indusstan_federation": "Federation of Indusstan",
  "dyn_c_bengal_federation": "Federation of Bengal",
  "dyn_c_cyberia": "Cyberia",
  "dyn_c_cyberia_adj": "Cyberian",
  "dyn_c_south_africa": "Cape Colony",
  "dyn_c_south_africa_adj": "Cape Colonies",
  "dyn_c_mahdist_state": "Mahdist State",
  "dyn_c_mahdist_state_adj": "Mahdist Sudanese",
  "dyn_c_scandinavia_kalmar_union": "Kalmar Union",
  "dyn_c_scandinavia_kalmar_union_adj": "Scandinavian",
  "dyn_c_gotland_revolt": "Gotland Revolt",
  "dyn_c_gotland_revolt_adj": "Gotlandic",
  "dyn_c_welsh_patagonia": "Y Wladfa",
  "dyn_c_welsh_patagonia_adj": "Welsh Patagonian",
  "dyn_c_peru_bolivia": "Peru-Bolivia",
  "dyn_c_peru_bolivia_adj": "Peruvian-Bolivian",
  "dyn_c_confederate_state_of_america": "Confederate State of America",
  "dyn_c_united_state": "United State of America",
  "dyn_c_qasimid_state": "Qasimid State",
  "dyn_c_qasimid_state_adj": "Qasimid",
  "dyn_c_funj_state": "Funj",
  "dyn_c_funj_state_adj": "Funj",
  "dyn_c_commonwealth": "Commonwealth",
  "dyn_c_commonwealth_adj": "Commonwealth",
  "dyn_c_empire_of_china": "Empire of China",
  "dyn_c_empire_of_china_adj": "Chinese",
  "dyn_c_louisiana": "$LOU$",
  "dyn_c_new_france": "New France",
  "dyn_c_new_france_adj": "New French",
  "dyn_c_louisiana_commune": "Louisiana Commune",
  "dyn_c_archbishopric_of_st_louis": "St. Louis",
  "dyn_c_regency_of_algiers": "Regency of Algiers",
  "dyn_c_regency_of_algiers_adj": "Algerian",
  "dyn_c_barbary_adj": "Barbary",
  "dyn_c_maghreb": "Maghreb",
  "dyn_c_maghreb_adj": "Maghrebi",
  "dyn_c_bengal_presidency": "Bengal Presidency",
  "dyn_c_madras_presidency": "Madras Presidency",
  "dyn_c_bombay_presidency": "Bombay Presidency",
  "dyn_c_croatia_slavonia": "Croatia-Slavonia",
  "dyn_c_bulgarian_empire": "Bulgarian Empire",
  "dyn_c_bulgarian_empire_adj": "Imperial Bulgarian",
  "dyn_c_iberian_union": "Iberian Union",
  "dyn_c_iberian_union_def": "the $dyn_c_iberian_union$",
  "dyn_c_iberian_federation": "Iberian Federation",
  "dyn_c_iberian_federation_def": "the $dyn_c_iberian_federation$",
  "dyn_c_iberian_confederation": "Iberian Confederation",
  "dyn_c_iberian_confederation_def": "the $dyn_c_iberian_confederation$",
  "dyn_c_iberian_concordat": "Iberian Concordat",
  "dyn_c_iberian_concordat_def": "the $dyn_c_iberian_concordat$",
  "dyn_c_esperantia": "Esperantia",
  "dyn_c_esperantia_adj": "Esperantia",
  "dyn_c_aggressor": "Aggressor",
  "dyn_c_aggressor_adj": "Aggressor",
  "dyn_c_muhammara": "Muhammara",
  "dyn_c_muhammara_adj": "Kaabi",
  "dyn_c_iran": "Iran",
  "dyn_c_iran_adj": "Iranian",
  "dyn_c_durrani_empire": "Durrani Empire",
  "dyn_c_durrani_empire_adj": "Durrani",
  "dyn_c_majapahit": "Majapahit",
  "dyn_c_majapahit_adj": "Majapahit",
  "dyn_c_srivijaya": "Srivijaya",
  "dyn_c_srivijaya_adj": "Srivijayan",
  "dyn_c_sumatra": "Sumatra",
  "dyn_c_sumatra_adj": "Sumatran",
  "dyn_c_kalimantan": "Kalimantan",
  "dyn_c_kalimantan_adj": "Kalimantan",
  "dyn_c_boni": "Bo-Ni",
  "dyn_c_boni_adj": "Bo-Ni",
  "dyn_c_mataram": "Mataram",
  "dyn_c_mataram_adj": "Mataram",
  "dyn_c_jodhpur": "Jodhpur",
  "dyn_c_jodhpur_adj": "Jodhpuri",
  "dyn_c_udaipur": "Udaipur",
  "dyn_c_udaipur_adj": "Udaipuri",
  "dyn_c_oudh": "Oudh",
  "dyn_c_oudh_adj": "Oudhi",
  "dyn_c_jaipur": "Jaipur",
  "dyn_c_jaipur_adj": "Jaipuri",
  "dyn_c_tran_ninh": "Tran Ninh",
  "dyn_c_tran_tay_thanh": "Tran Tay Thanh",
  "dyn_c_usga": "United States of Greater Austria",
  "dyn_c_serbian_montenegro": "Serbia and Montenegro",
  "dyn_c_serbian_montenegro_adj": "Serbian Montenegrin",
  "dyn_c_lombardy_venetia": "Lombardy-Venetia",
  "dyn_c_lombardy_venetia_adj": "Lombardy-Venetian",
  "dyn_c_venetia_lombardy": "Venetia-Lombardy",
  "dyn_c_venetia_lombardy_adj": "Venetian-Lombard",
  "dyn_c_venice_republic": "Most Serene Republic of Venice",
  "dyn_c_empire_of_haiti": "Empire of Haiti",
  "dyn_c_serbian_voivodeship": "Serbian Voivodship",
  "dyn_c_serbian_voivodeship_adj": "Serbian Voivodship",
  "dyn_c_federal_state_of_austria": "Federal State of Austria",
  "dyn_c_british_west_africa": "British West Africa",
  "dyn_c_british_west_africa_adj": "British",
  "dyn_c_kuk_communist": "Internationale Räterepublik",
  "dyn_c_illyria": "Illyria",
  "dyn_c_illyria_adj": "Illyrian",
  "dyn_c_spanish_republic": "Spanish Republic",
  "dyn_c_antilles_union": "Antillean Union",
  "dyn_c_tokugawa_shogunate": "Tokugawa Shogunate",
  "dyn_c_japanese_taikunate": "Japanese Taikunate",
  "dyn_c_japan_shogunate": "Japanese Shogunate",
  "dyn_c_japan_shogunate_adj": "Japanese",
  "dyn_c_empire_of_japan": "Empire of Japan",
  "dyn_c_empire_of_japan_adj": "Japanese",
  "dyn_c_republic_of_japan": "Republic of Japan",
  "dyn_c_republic_of_japan_adj": "Japanese",
  "dyn_c_ezo_government": "Ezo Government",
  "dyn_c_ezo_republic": "Ezo Republic",
  "dyn_c_earth_kingdom": "Earth Kingdom",
  "dyn_c_earth_republic": "Earth Republic",
  "dyn_c_taiping_republic": "Heavenly Republic",
  "dyn_c_gbr_monarchy": "United Kingdom",
  "dyn_c_kingdom_of_france": "Kingdom of France",
  "dyn_c_imperial_federation": "Imperial Federation",
  "dyn_c_imperial_federation_socialist": "Global Socialist Federation",
  "dyn_c_north_italian_federation": "North Italian Federation",
  "dyn_c_north_italian_federation_adj": "North Italian",
  "dyn_c_north_italian_theocracy_federation": "Italian Concordat League",
  "dyn_c_sic_republica_garibaldina": "Republica Garibaldina",
  "dyn_c_sic_republica_garibaldina_adj": "Garibaldino",
  "dyn_c_ita_republica_garibaldina": "Republica Italica Garibaldina",
  "dyn_c_ita_republica_garibaldina_adj": "Garibaldino",
  "dyn_c_ita_patria_imperiale": "Patria Imperiale Italica",
  "dyn_c_ita_patria_imperiale_adj": "Roman",
  "dyn_c_ita_corporate": "National Republican State of Italy",
  "dyn_c_ita_communist": "Italian People's Republic",
  "dyn_c_ita_empire_monarchy": "Italian Empire",
  "dyn_c_ita_empire_theocracy": "Imperium Italicum",
  "dyn_c_ita_empire_corporate": "Imperial State of Italy",
  "dyn_c_ita_empire_grand_republic": "Grand Republic of Italy",
  "dyn_c_ita_empire_comuni": "Comuni Uniti d'Italia",
  "dyn_c_ita_empire_vanguard": "People's Revolutionary Republic of Italy",
  "dyn_c_ita_empire_people_republic": "People's Revolutionary Republic of Italy",
  "dyn_c_ita_empire_dictatorship": "Imperial Republic of Italy",
  "dyn_c_ita_republic": "Italian Republic",
  "dyn_c_volga_socialist_republic": "Volga Socialist Republic",
  "dyn_c_volga_socialist_republic_adj": "Volga German",
  "dyn_c_far_east_german_state": "Far East German State",
  "dyn_c_far_east_german_state_adj": "Volga German",
  "dyn_c_kingdom_of_the_caribbean": "Kingdom of the Caribbean",
  "dyn_c_caribbean_socialist_republics": "Caribbean Socialist Republics",
  "dyn_c_caribbean_free_states": "Caribbean Free States",
  "dyn_c_caribbean_state": "Caribbean State",
  "dyn_c_kingdom_of_the_caribbean_adj": "Caribbean",
  "dyn_c_caribbean_socialist_republics_adj": "Caribbean",
  "dyn_c_caribbean_free_states_adj": "Caribbean",
  "dyn_c_caribbean_state_adj": "Caribbean",
  "dyn_c_holy_global_federation": "Holy Global Federation",
  "dyn_c_holy_global_federation_adj": "Holy Global",
  "dyn_c_global_socialist_federation": "Global Socialist Federation",
  "dyn_c_global_socialist_federation_adj": "Global Federation",
  "dyn_c_global_anarchist_society": "Global Anarchist Society",
  "dyn_c_global_anarchist_society_adj": "Global",
  "dyn_c_free_roman_lands": "Free Roman Lands",
  "dyn_c_free_roman_lands_adj": "Roman",
  "dyn_c_romanian_bulgarian_empire": "Romanian–Bulgarian Empire",
  "dyn_c_romanian_bulgarian_empire_adj": "Romanian–Bulgarian",
  "dyn_c_bulgarian_wallachian_empire": "Bulgarian–Wallachian Empire",
  "dyn_c_bulgarian_wallachian_empire_adj": "Bulgarian–Wallachian",
  "dyn_c_ursal": "Union of Socialist Republics of Latin America",
  "dyn_c_ursal_adj": "URSAL",
  "dyn_c_kingdom_of_jerusalem": "Kingdom of Jerusalem",
  "dyn_c_kingdom_of_jerusalem_adj": "Jerusalem",
  "dyn_c_east_african_federation": "East African Federation",
  "dyn_c_east_african_federation_adj": "East African",
  "dyn_c_east_african_commune": "East African Commune",
  "dyn_c_east_african_commune_adj": "East African",
  "dyn_c_east_african_kingdom": "East African Empire",
  "dyn_c_east_african_kingdom_adj": "East African",
  "dyn_c_pacific_kingdom": "Pacific Kingdom",
  "dyn_c_pacific_kingdom_adj": "Pacific",
  "dyn_c_pacific_commune": "Pacific Commune",
  "dyn_c_pacific_commune_adj": "Pacific",
  "dyn_c_cascadian_kingdom": "Cascadian Kingdom",
  "dyn_c_cascadian_kingdom_adj": "Cascadian",
  "dyn_c_kingdom_of_the_great_lakes": "Kingdom of the Great Lakes",
  "dyn_c_kingdom_of_the_great_lakes_adj": "Great Lakes",
  "dyn_c_great_lakes_communes": "Great Lakes Communes",
  "dyn_c_great_lakes_communes_adj": "Great Lakes",
  "dyn_c_ocean_kingdom": "Coastal Kingdom",
  "dyn_c_ocean_kingdom_adj": "Coastal",
  "dyn_c_tide_communist_state": "Tide Communist State",
  "dyn_c_tide_communist_state_adj": "Tidal",
  "dyn_c_mountain_kingdom": "Appalachian Kingdom",
  "dyn_c_mountain_kingdom_adj": "Appalachian",
  "dyn_c_appalachian_commune": "Appalachian Commune",
  "dyn_c_appalachian_commune_adj": "Appalachian",
  "dyn_c_atlantis": "Atlantis",
  "dyn_c_atlantis_adj": "Atlantic",
  "dyn_c_atlantic_society": "Atlantic Society",
  "dyn_c_atlantic_society_adj": "Atlantic",
  "dyn_c_arixo_kingdom": "Arixo Kingdom",
  "dyn_c_arixo_kingdom_adj": "Arixan",
  "dyn_c_kingdom_of_the_rockies": "Kingdom of the Rockies",
  "dyn_c_kingdom_of_the_rockies_adj": "Rocky",
  "dyn_c_rock_community": "Rock Community",
  "dyn_c_rock_community_adj": "Rocky",
  "dyn_c_great_plains_kingdom": "Great Plains Kingdom",
  "dyn_c_great_plains_kingdom_adj": "Great Plain",
  "dyn_c_great_plains_communes": "Great Plains Communes",
  "dyn_c_great_plains_communes_adj": "Great Plain",
  "dyn_c_southern_kingdom": "Southern Kindgom",
  "dyn_c_southern_kingdom_adj": "Southern",
  "dyn_c_southern_communes": "Southern Commune",
  "dyn_c_southern_communes_adj": "Southern",
  "dyn_c_new_brittain": "New Britain",
  "dyn_c_thirteen_communes": "Thirteen Communes",
  "dyn_c_thirteen_communes_adj": "Communal",
  "dyn_c_arctic_kindom": "Arctic Kindgom",
  "dyn_c_arctic_kindom_adj": "Arctic",
  "dyn_c_arctic_society": "Arctic Society",
  "dyn_c_hyperborea": "Hyperborea",
  "dyn_c_hyperborea_adj": "Hyperborean",
  "dyn_c_angevin_republic": "Dual Republic",
  "dyn_c_angevin_republic_adj": "Dual",
  "dyn_c_channel_council": "Channel Council",
  "dyn_c_channel_council_adj": "Channel",
  "dyn_c_portugal_galicia": "Portugaliza",
  "dyn_c_portugal_galicia_adj": "Portugalizan",
  "dyn_c_denmark_norway": "Denmark-Norway",
  "dyn_c_denmark_norway_adj": "Dano-Norwegian",
  "dyn_c_alpine_kingdom": "Alpine Empire",
  "dyn_c_alpine_kingdom_adj": "Alpine",
  "dyn_c_alpine_commune": "Alpine Commune",
  "dyn_c_alpine_commune_adj": "Alpine",
  "dyn_c_alpine_see": "Alpine See",
  "dyn_c_alpine_see_adj": "Alpine",
  "dyn_c_baltic_state": "Baltic State",
  "dyn_c_baltic_state_adj": "Baltic German",
  "dyn_c_baltic_german_union": "Baltic German Union",
  "dyn_c_baltic_german_union_adj": "Baltic German",
  "dyn_c_levantine_federation": "Levantine Federation",
  "dyn_c_levantine_federation_adj": "Levantine",
  "dyn_c_levantine_kingdom": "Levantine Kingdom",
  "dyn_c_levantine_kingdom_adj": "Levantine",
  "dyn_c_levantine_union": "Union of the Levant",
  "dyn_c_levantine_union_adj": "Levantine",
  "dyn_c_levantine_state": "Levantine State",
  "dyn_c_levantine_state_adj": "Levantine",
  "dyn_c_italo_spanish_union": "Italo-Spanish Union",
  "dyn_c_italo_spanish_union_adj": "Italo-Spanish",
  "dyn_c_italo_spanish_republic": "Italo-Spanish Republic",
  "dyn_c_italo_spanish_republic_adj": "Italo-Spanish",
  "dyn_c_kingdom_of_trebizond": "Trebizond",
  "dyn_c_kingdom_of_trebizond_adj": "Trebizond",
  "dyn_c_lusitanian_union": "Lusitanian Union",
  "dyn_c_lusitanian_union_adj": "Lusitanian",
  "dyn_c_united_republic": "United Republic",
  "dyn_c_united_republic_adj": "Lusitanian",
  "dyn_c_thunder_dragon_empire": "Thunder Dragon Empire",
  "dyn_c_thunder_dragon_empire_adj": "Bhutanese",
  "dyn_c_united_kingdom_brz": "United Kingdom of Brazil and Portugal",
  "dyn_c_united_kingdom_por": "United Kingdom of Portugal and Brazil",
  "dyn_c_spanish_kingdom": "Kingdom of Spain",
  "dyn_c_spanish_empire": "Spanish Empire",
  "dyn_c_fascist_france": "French State",
  "dyn_c_russian_empire": "Russian Empire",
  "dyn_c_slavia_communist": "Union of Soviet Slavic Republics",
  "dyn_c_slavic_empire": "Empire of Slavia",
  "dyn_c_slavic_republic": "Federal Republic of Slavia",
  "dyn_c_roman_republic_adj": "Roman",
  "dyn_c_kingdom_italy": "Kingdom of Italy",
  "dyn_c_holy_italy": "Holy State of Italy",
  "dyn_c_empire_italy": "Italian Empire",
  "dyn_c_imperial_japan": "Imperial Japan",
  "dyn_c_japanese_china": "Reorganized China",
  "dyn_c_shogunate_of_japan": "Shogunate of Japan",
  "dyn_c_theocracy_japan": "Heavenly Realm of Japan",
  "dyn_c_german_reich": "German Reich",
  "dyn_c_prussia_monarchy": "Kingdom of Prussia",
  "dyn_c_german_republic": "German Republic",
  "dyn_c_austrian_empire": "Empire of Austria",
  "dyn_c_dual_monarchy": "Austria-Hungary",
  "dyn_c_triple_monarchy": "Austria-Hungary-Croatia",
  "dyn_c_danubian_federation": "Danubian Federation",
  "dyn_c_german_confederation": "German Confederation",
  "dyn_c_kalmar_union": "Kalmar Union",
  "dyn_c_kalmar_union_adj": "Kalmar",
  "dyn_c_kalmar_republic": "Kalmar Federation",
  "dyn_c_kalmar_commune": "Kalmar Commune",
  "dyn_c_kalmar_corporate_state": "Kalmar Syndicate",
  "dyn_c_scandinavia_monarchy": "Scandinavian Empire",
  "dyn_c_scandinavia_council_republic": "Scandinavian People's Federation",
  "dyn_c_alawite_empire": "Alawite Empire",
  "dyn_c_alawite_empire_adj": "Alawite"
}
