// Generated from Victoria 3 vanilla English localization and tyrone-mp English localization.
// Vanilla is loaded first; tyrone-mp overrides win on duplicate law keys.
export const LAW_LOCALIZATION: Record<string, string> = {
  "law_affirmative_action": "Affirmative Action",
  "law_agrarianism": "Agrarianism",
  "law_anarchy": "Anarchy",
  "law_ancien_regime": "The Ancien Régime",
  "law_anti_strike_laws": "Anti-Strike Laws",
  "law_appointed_bureaucrats": "Appointed Bureaucrats",
  "law_atheist_state": "Atheist State",
  "law_autocracy": "Autocracy",
  "law_bakufu": "Bakufu",
  "law_canton_system": "Canton System",
  "law_censorship": "Censorship",
  "law_census_voting": "Census Suffrage",
  "law_changed_notification_group": "Law Changed",
  "law_charitable_health_system": "Charity Hospitals",
  "law_chiefdom": "Chiefdom",
  "law_chiefs_distribute_aid": "Šef Paternalism",
  "law_child_labor_allowed": "Child Labor Allowed",
  "law_closed_borders": "Closed Borders",
  "law_collectivized_agriculture": "Collectivized Agriculture",
  "law_colonial_administration": "Colonial Administration",
  "law_colonial_exploitation": "Colonial Exploitation",
  "law_colonial_resettlement": "Colonial Resettlement",
  "law_colonial_slavery": "Colonial Slavery",
  "law_combination_acts": "Combination Acts",
  "law_command_economy": "Command Economy",
  "law_commercialized_agriculture": "Commercialized Agriculture",
  "law_commitment": "Law Commitment",
  "law_compulsory_primary_school": "Compulsory Primary School",
  "law_consumption_based_taxation": "Consumption-Based Taxation",
  "law_cooperative_ownership": "Cooperative Ownership",
  "law_corporate_state": "Corporate State",
  "law_corporatized_unions": "Corporatized Unions",
  "law_council_republic": "Council Republic",
  "law_crownland_diets": "Crownland Diets",
  "law_cultural_exclusion": "Cultural Exclusion",
  "law_cultuurstelsel": "Cultuurstelsel",
  "law_debt_slavery": "Debt Slavery",
  "law_dedicated_police": "Dedicated Police Force",
  "law_diplomatic_navy": "Diplomatic Fleet",
  "law_disability_insurance": "Disability Insurance",
  "law_dismentling_the_state": "Dismantling the State",
  "law_elder_council": "Elder Council",
  "law_elected_bureaucrats": "Elected Bureaucrats",
  "law_enactment_chance": "Law Enactment Chance",
  "law_enforcement": "Law Enforcement",
  "law_ethnostate": "Ethnostate",
  "law_expanded_latifundias": "Expanded Latifundias",
  "law_extraction_economy": "Extraction Economy",
  "law_factory_councils": "Factory Councils",
  "law_first_past_the_post": "First Past The Post",
  "law_free_trade": "Free Trade",
  "law_freedom_of_conscience": "Freedom of Conscience",
  "law_frontier_colonization": "Frontier Colonization",
  "law_full_womens_rights": "Full Women's Rights",
  "law_graduated_taxation": "Graduated Taxation",
  "law_guaranteed_liberties": "Guaranteed Liberties",
  "law_guild_system": "Guild System",
  "law_hereditary_bureaucrats": "Hereditary Bureaucrats",
  "law_hindu_caste_codified": "Caste System Codified",
  "law_hindu_caste_enforced": "Caste System Enforced",
  "law_hindu_caste_not_enforced": "Caste Not Enforced",
  "law_homesteading": "Homesteading",
  "law_imperial_federal_bureaucracy": "Imperial Federal Bureaucracy",
  "law_imposition_already_enacting_law": "We are #b not#! already enacting the proposed law",
  "law_industry_banned": "Industry Banned",
  "law_intermediate_edo_system": "Loosened Status Order",
  "law_interventionism": "Interventionism",
  "law_isolationism": "Isolationism",
  "law_jeune_ecole": "Jeune École",
  "law_laissez_faire": "Laissez-Faire",
  "law_laissez_faire_plus": "Financial Corporatism",
  "law_laissez_faire_subject": "Monopoly Allowed",
  "law_land_based_taxation": "Land-Based Taxation",
  "law_landed_voting": "Landed Voting",
  "law_latifundias": "Latifundias",
  "law_lax_edo_system": "Lax Status Order",
  "law_legacy_slavery": "Legacy Slavery",
  "law_local_police": "Local Police Force",
  "law_manorialism": "Manorialism",
  "law_mass_conscription": "Mass Conscription",
  "law_mercantilism": "Mercantilism",
  "law_merchant_navy": "Merchant Navy",
  "law_meritocratic_bureaucracy": "Meritocratic Bureaucracy",
  "law_migration_controls": "Migration Controls",
  "law_militarized_police": "Militarized Police Force",
  "law_millet_system": "Millet System",
  "law_monarchy": "Monarchy",
  "law_multicultural": "Multiculturalism",
  "law_national_guard": "National Guard",
  "law_national_militia": "National Militia",
  "law_national_supremacy": "National Supremacy",
  "law_neo_absolutism": "Neo-Absolutism",
  "law_neofeudalism": "Neofeudalism",
  "law_no_colonial_affairs": "No Colonial Affairs",
  "law_no_health_system": "No Health System",
  "law_no_home_affairs": "No Home Affairs",
  "law_no_migration_controls": "No Migration Controls",
  "law_no_police": "No Police",
  "law_no_schools": "No Schools",
  "law_no_social_security": "No Social Security",
  "law_no_womens_rights": "Legal Guardianship",
  "law_no_workers_rights": "No Workers' Rights",
  "law_notification_group": "Law Progression",
  "law_old_age_pension": "Old Age Pension",
  "law_oligarchy": "Oligarchy",
  "law_organic_regulation": "Organic Regulation",
  "law_outlawed_dissent": "Outlawed Dissent",
  "law_parliamentary_republic": "Parliamentary Republic",
  "law_peasant_levies": "Peasant Levies",
  "law_peasant_proprietorship": "Peasant Proprietorship",
  "law_people_of_the_book": "People of the Book",
  "law_per_capita_based_taxation": "Per-Capita Taxation",
  "law_poor_laws": "Poor Laws",
  "law_presidential_republic": "Presidential Republic",
  "law_private_health_insurance": "Private Health Insurance",
  "law_private_schools": "Private Schools",
  "law_professional_army": "Professional Army",
  "law_professional_navy": "Capital Fleet",
  "law_proportional_representation": "Proportional Representation",
  "law_proportional_taxation": "Proportional Taxation",
  "law_protected_speech": "Protected Speech",
  "law_protectionism": "Protectionism",
  "law_public_health_insurance": "Public Health Insurance",
  "law_public_schools": "Public Schools",
  "law_racial_segregation": "Racial Segregation",
  "law_regulatory_bodies": "Regulatory Bodies",
  "law_religious_schools": "Religious Schools",
  "law_restricted_child_labor": "Restricted Child Labor",
  "law_right_of_assembly": "Right of Assembly",
  "law_right_to_associate": "Right to Associate",
  "law_sakoku": "Sakoku",
  "law_secret_police": "Secret Police",
  "law_serfdom": "Serfdom",
  "law_shinsengumi": "Shinsengumi",
  "law_sic_agrarian_reform": "The Reformed Agrarian Order",
  "law_sic_serfdom": "Bonded Peasantry",
  "law_sic_slave_trade": "The Controlled Bondage Regime",
  "law_single_party_state": "Single-Party State",
  "law_slave_trade": "Slave Trade",
  "law_slavery_banned": "Slavery Banned",
  "law_social_monarchy": "Social Monarchy",
  "law_state_atheism": "State Atheism",
  "law_state_capitalism": "State Capitalism",
  "law_state_religion": "State Religion",
  "law_strict_edo_system": "Rigid Status Order",
  "law_subjecthood": "Subjecthood",
  "law_technocracy": "Technocracy",
  "law_tenant_farmers": "Tenant Farmers",
  "law_terakoya": "Terakoya",
  "law_theocracy": "Theocracy",
  "law_total_separation": "Total Separation",
  "law_traditionalism": "Traditionalism",
  "law_two_years_tt": "Penalties will be reduced if [ROOT.GetCountry.GetName] attempts to enact [SCOPE.sLaw('government_petition_law').GetName] for at least #v 24 months#!. \\n#v Current failure effects:#!",
  "law_universal_suffrage": "Universal Suffrage",
  "law_wage_subsidies": "Wage Subsidies",
  "law_warrior_caste": "Warrior Caste",
  "law_wealth_voting": "Wealth Voting",
  "law_women_in_the_fields": "Women in the Fields",
  "law_women_in_the_fields_is_in_effect_tt": "While the [GetLawType('law_women_in_the_fields').GetName] [concept_law] is active, Montenegro will have more soldiers and workers available, but its people will suffer.",
  "law_women_in_the_workplace": "Women in the Workplace",
  "law_women_own_property": "Propertied Women",
  "law_womens_suffrage": "Women’s Suffrage",
  "law_worker_protections": "Workers' Protections",
}

export const LAW_LOCALIZATION_COUNT = 163
